#!/usr/bin/env bash
#
# nicsdru-logging/scripts/example.cronjob.sh
#
# Calls shiplog.sh to ship latest log entries from various logs
# to logz.io.

# /bin/bash /app/nicsdru-logging/scripts/shiplog.sh "[LOG_NAME]" "[LOG_PATH]" "[LOG_DATE_PATTERN]" "[LOG_TYPE]"

# Ship /var/log/access.log generated by nginx.
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "access" "/var/log/access.log" "$(date +%d/%b/%Y:)" "nginx_access"

# Uncomment following line to ship drupal.log generated by D9 filelog module.
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-infolibrarynics" "/app/log/infolibrarynics/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-pressclippingsnics" "/app/log/pressclippingsnics/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-parolecomni" "/app/log/parolecomni/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-lgbcni" "/app/log/lgbcni/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-semcommittee" "/app/log/semcommittee/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-boundarycommission" "/app/log/boundarycommission/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-pacni" "/app/log/pacni/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-interchangeni" "/app/log/interchangeni/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
/bin/bash /app/nicsdru-logging/scripts/shiplog.sh "drupal-industrialcourt" "/app/log/industrialcourt/drupal.log" "$(date +'%a, %d/%m/%Y -')" "drupal"
