<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_form_alter().
 */
function interchangeni_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_manager_form' || $form_id == 'node_manager_edit_form') {
    $form['title']['#disabled'] = 'disabled';
    $form['title']['widget'][0]['value']['#description'] = t('You cannot edit this field. It is created automatically using the Surname and the First name.');

  }
}


/**
 * Implements hook_entity_presave().
 */
function interchangeni_common_entity_presave(EntityInterface $entity) {
  // This will fire when nodes are created or edited.
  if ($entity instanceof NodeInterface && $entity->bundle() === 'manager') {

    $first_name = $entity->get('field_first_name')->value;
    $last_name = $entity->get('field_last_name')->value;
    $node_title = $first_name . ' ' . $last_name;

    $entity->setTitle($node_title);
  }
}
