_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 75c3f9d4-2a49-4df0-b22d-bdaeee4177fc
name: 'NICS e-library'
mail: nicslibrary@finance-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to NICS e-library'
frontpage_show_title: 0
