_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 0f652bed-edfc-491a-ae0e-327f97e5baef
name: 'Civil Service Commissioners for Northern Ireland'
mail: info@nicscommissioners.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Civil Service Commissioners for Northern Ireland'
frontpage_show_title: 0
