popup_info:
  value: "<p>Cookies on the [site:name] website</p>\r\n\r\n<p>We use some essential cookies to make this service work. We'd like to set additional cookies so we can remember your settings, understand how people use the service and make improvements. Some of our pages allow selected third parties to set cookies - for example, pages that contain YouTube videos or Google Maps.</p>\r\n\r\n<p><a href=\"/cookies\">Find out more about how we use cookies</a></p>\r\n"
popup_agree_button_message: 'Accept cookies'
popup_more_info_button_message: 'Find out more about how we use cookies'
disagree_button_label: 'Reject cookies'
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
popup_find_more_button_message: 'More info'
popup_hide_button_message: Hide
popup_link: '<front>'
withdraw_message:
  value: "<p>Cookies on the [site:name] website</p>\r\n\r\n<p>You have given your consent for us to set additional cookies&nbsp;so we can remember your settings, understand how people use the service and make improvements.&nbsp; If you have changed your mind, you can withdraw consent.</p>\r\n\r\n<p><a href=\"/cookies\">Find out more about how we use cookies</a></p>\r\n"
withdraw_tab_button_label: 'Cookie settings'
withdraw_action_button_label: 'Withdraw consent'
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
