_core:
  default_config_hash: HjgzralR15mPYGRNbqNksKwS6P-nDR6oMU1Q39hpnBk
langcode: en
allow_insecure_uploads: false
default_scheme: public
temporary_maximum_age: 21600
filename_transliteration: true
