_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: da1ec085-4c7b-43e8-8604-d489ef06e787
name: Liofa
mail: webmaster@liofa.eu
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Liofa'
frontpage_show_title: 0
