<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_alter().
 */
function judiciaryni_common_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_judicial_member_form' || $form_id == 'node_judicial_member_edit_form') {
    $form['title']['#disabled'] = 'disabled';
    $form['title']['widget'][0]['value']['#description'] = t('You cannot edit this field. It is created automatically using the Name of Judge and Judicial Tier.');

  }
}


/**
 * Implements hook_entity_presave().
 */
function judiciaryni_common_entity_presave(EntityInterface $entity) {
  // This will fire when nodes are created or edited.
  if ($entity instanceof NodeInterface && $entity->bundle() === 'judicial_member') {

    $judge_name = $entity->get('field_surname')->value;
    $judge_sex = $entity->get('field_sex_of_member')->value;
    $tier_tid = $entity->get('field_judicial_tier')->target_id;
    $judge_title = ucfirst($entity->get('field_prefix_title')->value);
    $short_title = $judge_title . ' ' . $judge_name;

    if (!empty($tier_tid)) {
      $tier = Term::load($tier_tid);
      $tier_name = $tier->getName();

      if ($judge_title === 'Vacant') {
        $short_title = $judge_name . ' ' . $tier_name;
      }
      else {
        judiciaryni_common_switch_tier($tier_name, $short_title, $judge_name, $judge_sex);
      }
    }
    $entity->setTitle($short_title);
  }
}

/**
 * Utility function to add a Judge postfix based on their judicial tier.
 */
function judiciaryni_common_switch_tier($tier_name, &$short_title, $judge_name, $judge_sex) {
  switch ($tier_name) {
    case 'Lord Chief Justice':
    case 'Lady Chief Justice':
      $short_title = $judge_name . t(' LCJ');
      break;

    case 'Justice of Appeal':
      $short_title = $judge_name . t(' LJ');
      break;

    case 'High Court Judge':
      $short_title = $judge_name . t(' J');
      break;

    case 'Temporary High Court Judge':
      $short_title = $short_title . t(' sitting as HCJ');
      break;

    case 'County Court Judge':
    case 'Recorder of Belfast':
    case 'Recorder of Londonderry':
      $sex = t('His ');
      if ($judge_sex !== 'male') {
        $sex = t('Her ');
      }
      $short_title = $sex . t('Honour Judge ') . $judge_name;
      break;

    case 'Master of the High Court':
      $short_title = t('Master ') . $judge_name;
      break;

    case 'District Judge';
      $short_title = t('District Judge ') . $judge_name;
      break;

    case 'District Judge (Magistrates’ Courts)':
    case 'Presiding District Judge (Magistrates’ Courts)':
      $short_title = t('District Judge (MC) ') . $judge_name;
      break;
  }
}
