display:
  default:
    display_options:
      empty:
        area:
          content:
            value: '<p>Sorry, no classes/groups are currently listed.</p>'
            format: basic_html
      title: 'Ranganna Gaeilge'
  irish_language_groups:
    display_options:
      title: 'Grúpaí Gaeilge'
