_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: b00ef3b7-244c-4131-848c-a16ea07a6877
name: 'The Single Electricity Market Committee'
mail: Test@test.com
slogan: 'The decision making authority for the Single Electricity Market on the island of Ireland'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: 0
