_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: f4aca5e2-7993-4db4-812b-244015902258
name: 'Northern Ireland Bureau'
mail: info@nibureau.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: 0
