_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 78765322-fa2b-444f-90d6-0510cccb5ffc
name: 'Press Clippings Service'
mail: cutsteam@finance-ni.gov.uk
slogan: ''
page:
  403: /user/login
  404: ''
  front: /press-clippings
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Press Clippings Service'
frontpage_show_title: 1
